FROM node:14

RUN apt-get update && apt-get install -y tcpdump

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8000

RUN chmod +x /usr/src/app/start-proxy.sh
CMD ["/usr/src/app/start-proxy.sh"]
