tshark -r ../captures/proxy_traffic.pcap \
  -o "tls.keys_list:ip,port,protocol,keyfile" \
  -Y "http" \
  -T fields \
  -e ip.src \
  -e ip.dst \
  -e tcp.srcport \
  -e tcp.dstport \
  -e http.request.method \
  -e http.request.full_uri \
  -e http.request.line \
  -e http.file_data \
  -o ssl.keylog_file:../keys.log \